---
title: "311_Final_Data_Dashboard"
author: "SAMM"
date: "2025-03-04"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
# setup chunk to set global options and load in libraries
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
pacman::p_load(tidyverse, stringr, shiny, readr)
```

```{r loading_data}
# dropbox direct download link to access large file (+2gb)
dataset_url <- "https://www.dropbox.com/scl/fi/os1x9i7sx1io5ura5fjti/311_DATA.csv?rlkey=quw01tcso6lz3u3vtx7seoalc&st=634psn3v&dl=1"

# read CSV directly from Dropbox
data <- read_csv(dataset_url)

# show first few rows to make sure data was read in correctly
head(data)
```

```{r}
# Convert date columns to Date format
data$`Created Date` <- as.Date(data$`Created Date`, format = "%m/%d/%Y")
data$`Closed Date` <- as.Date(data$`Closed Date`, format = "%m/%d/%Y")

missing_dates <- sum(is.na(data$`Created Date`) | is.na(data$`Closed Date`))
cat("Missing date values:", missing_dates, "\n")

#calculating the duration, ensuring no NA values are involved
data$Duration <- as.numeric(difftime(data$`Closed Date`, data$`Created Date`, units = "days"))

data <- data[!is.na(data$Duration), ]

```


```{r}
data_1 <- data[data$Duration >= 0, ]  # removing negative duration (how is this even possible)
summary(data_1$Duration)
```
```{r, echo=FALSE}
# Calculate the average duration per borough
avg_duration_per_borough <- aggregate(Duration ~ Borough, data = data, FUN = mean)

# View the results
print(avg_duration_per_borough)

```



```{r, echo=FALSE}
#creating plot for average duration per borough

ggplot(avg_duration_per_borough, aes(x = Borough, y = Duration)) +
  geom_bar(stat = "identity") + 
  labs(title = "Average Duration by Borough", y = "Average Duration (Days)", x = "Borough") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```




